# Generated by Django 4.2.5 on 2023-11-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorfees',
            old_name='total_fees',
            new_name='total_admin_fees',
        ),
        migrations.AddField(
            model_name='doctorfees',
            name='total_doctor_fees',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='AdminFees',
        ),
    ]
