# Generated by Django 4.2.5 on 2023-11-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_total_fees_doctorfees_total_admin_fees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorappointment',
            name='admin_fees',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='doctorappointment',
            name='doctor_fees',
            field=models.FloatField(null=True),
        ),
    ]
